# Generated by Django 3.1.7 on 2021-03-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_child_manager_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Цена пакета')),
                ('trainings_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во тренировок')),
                ('trainings_freeze_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во заморозок')),
            ],
        ),
        migrations.AlterField(
            model_name='child',
            name='trainings_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во тренировок'),
        ),
        migrations.AlterField(
            model_name='child',
            name='trainings_freeze_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во заморозок'),
        ),
        migrations.AlterField(
            model_name='preregisteruseremail',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email с приглашением'),
        ),
    ]
