# Generated by Django 3.1.7 on 2021-03-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_agecategory_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agecategory',
            name='max_age',
            field=models.PositiveIntegerField(verbose_name='Максимальный возраст'),
        ),
        migrations.AlterField(
            model_name='agecategory',
            name='min_age',
            field=models.PositiveIntegerField(verbose_name='Минимальный возраст'),
        ),
    ]
