# Generated by Django 3.1.7 on 2021-03-15 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210315_1429'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agecategory',
            unique_together={('min_age', 'max_age')},
        ),
        migrations.AlterUniqueTogether(
            name='pack',
            unique_together={('trainings_count', 'trainings_freeze_count')},
        ),
    ]
