# Generated by Django 3.1.7 on 2021-03-16 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210315_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отделения')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес отделения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение отделения')),
                ('pack', models.ManyToManyField(to='mainapp.Pack', verbose_name='Пакет отделения')),
                ('trainer', models.ManyToManyField(to='mainapp.Trainer', verbose_name='Тренер отделения')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.agecategory', verbose_name='Возрастная группа')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.department', verbose_name='Отделение')),
                ('trainer', models.ManyToManyField(to='mainapp.Trainer', verbose_name='Тренер группы')),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AlterField(
            model_name='news',
            name='header',
            field=models.CharField(max_length=255, verbose_name='Заголовок новости'),
        ),
    ]
