# Generated by Django 3.1.7 on 2021-03-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210316_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название отделения'),
        ),
    ]
