# Generated by Django 3.1.7 on 2021-03-16 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210316_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='pack',
        ),
        migrations.CreateModel(
            name='PackInDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.department', verbose_name='Отделение с пакетом')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.trainer', verbose_name='Пакет отделения')),
            ],
        ),
    ]
