# Generated by Django 3.1.7 on 2021-03-16 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210316_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packindepartment',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.pack', verbose_name='Пакет отделения'),
        ),
    ]
