# Generated by Django 3.1.7 on 2021-03-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20210316_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='A', max_length=255, verbose_name='Название группы'),
        ),
    ]
