# Generated by Django 3.1.7 on 2021-03-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20210316_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='pack',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.Pack', verbose_name='Пакеты отделения'),
        ),
        migrations.AlterField(
            model_name='department',
            name='trainer',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.Trainer', verbose_name='Тренеры отделения'),
        ),
    ]
