# Generated by Django 3.1.7 on 2021-03-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_group_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='group',
            field=models.ManyToManyField(to='mainapp.Group', verbose_name='Группы отделения'),
        ),
    ]
