# Generated by Django 3.1.7 on 2021-03-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20210316_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='group',
            field=models.ManyToManyField(blank=True, to='mainapp.Group', verbose_name='Группы отделения'),
        ),
        migrations.AlterField(
            model_name='department',
            name='pack',
            field=models.ManyToManyField(blank=True, to='mainapp.Pack', verbose_name='Пакеты отделения'),
        ),
        migrations.AlterField(
            model_name='department',
            name='trainer',
            field=models.ManyToManyField(blank=True, to='mainapp.Trainer', verbose_name='Тренеры отделения'),
        ),
    ]
