# Generated by Django 3.1.7 on 2021-03-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20210316_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение новости'),
        ),
    ]
