# Generated by Django 3.1.7 on 2021-03-16 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20210316_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=9, verbose_name='День тренировки')),
                ('starttime', models.TimeField(verbose_name='Время начала тренировки')),
                ('endtime', models.TimeField(verbose_name='Время окончания тренировки')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.department', verbose_name='Отделение')),
                ('group', models.ManyToManyField(to='mainapp.Group', verbose_name='Группы')),
            ],
        ),
    ]
