# Generated by Django 3.1.7 on 2021-03-16 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата тренировки')),
                ('starttime', models.TimeField(verbose_name='Время начала тренировки')),
                ('endtime', models.TimeField(verbose_name='Время окончания тренировки')),
                ('status', models.CharField(choices=[('not_stated', 'Неопределенное'), ('done', 'Выполнена'), ('not_took_place', 'Не состоялась')], default='not_stated', max_length=14, verbose_name='Состояние')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.department', verbose_name='Отделение')),
                ('group', models.ManyToManyField(to='mainapp.Group', verbose_name='Группы')),
            ],
        ),
    ]
