# Generated by Django 3.1.7 on 2021-03-16 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20210316_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.group', verbose_name='Группа'),
        ),
    ]
