# Generated by Django 3.1.7 on 2021-03-16 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20210316_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildOnTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.child', verbose_name='Ребенок на тренировке')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.training', verbose_name='Тренировка')),
            ],
            options={
                'unique_together': {('child', 'training')},
            },
        ),
    ]
