# Generated by Django 3.1.7 on 2021-03-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_childontraining'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('day', 'department', 'starttime', 'endtime')},
        ),
        migrations.AlterUniqueTogether(
            name='training',
            unique_together={('date', 'department', 'group', 'starttime', 'endtime', 'status')},
        ),
    ]
