# Generated by Django 3.1.7 on 2021-03-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_auto_20210316_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='childontraining',
            name='reserve_trainers',
            field=models.ManyToManyField(to='mainapp.Trainer', verbose_name='Заменяющие тренеры'),
        ),
    ]
