# Generated by Django 3.1.7 on 2021-03-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_childontraining_reserve_trainers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childontraining',
            name='reserve_trainers',
            field=models.ManyToManyField(default=None, to='mainapp.Trainer', verbose_name='Заменяющие тренеры'),
        ),
    ]
