# Generated by Django 3.1.7 on 2021-03-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20210316_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childontraining',
            name='reserve_trainers',
        ),
        migrations.AddField(
            model_name='training',
            name='reserve_trainers',
            field=models.ManyToManyField(default=None, to='mainapp.Trainer', verbose_name='Заменяющие тренеры'),
        ),
    ]
