# Generated by Django 3.1.7 on 2021-03-16 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_auto_20210316_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childontraining',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.training', verbose_name='Тренировка'),
        ),
        migrations.AlterField(
            model_name='training',
            name='reserve_trainers',
            field=models.ManyToManyField(blank=True, default=None, to='mainapp.Trainer', verbose_name='Заменяющие тренеры'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.child', verbose_name='Ребенок')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.pack', verbose_name='Пакет')),
            ],
            options={
                'unique_together': {('timestamp', 'child', 'pack')},
            },
        ),
    ]
