# Generated by Django 3.1.7 on 2021-03-16 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_auto_20210316_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agecategory',
            options={'verbose_name_plural': 'Категории возрастов'},
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name_plural': 'Дети'},
        ),
        migrations.AlterModelOptions(
            name='childontraining',
            options={'verbose_name_plural': 'Дети на тренировках'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Отделения'},
        ),
        migrations.AlterModelOptions(
            name='galery',
            options={'verbose_name_plural': 'Галереи'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name_plural': 'Менеджеры'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='pack',
            options={'verbose_name_plural': 'Пакеты тренировок'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'Люди'},
        ),
        migrations.AlterModelOptions(
            name='photoingalery',
            options={'verbose_name_plural': 'Фотографии в галерее'},
        ),
        migrations.AlterModelOptions(
            name='preregisteruseremail',
            options={'verbose_name_plural': 'Предрегистрационные почтовые адреса'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name_plural': 'Тренера'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name_plural': 'Тренировки'},
        ),
    ]
