# Generated by Django 3.1.7 on 2021-03-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_auto_20210316_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
