# Generated by Django 3.1.7 on 2021-03-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_galery_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
