# Generated by Django 3.1.7 on 2021-03-19 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_auto_20210317_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name_plural': 'Тренеры'},
        ),
        migrations.AlterField(
            model_name='group',
            name='children',
            field=models.ManyToManyField(blank=True, to='mainapp.Child', verbose_name='Дети группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='trainer',
            field=models.ManyToManyField(blank=True, to='mainapp.Trainer', verbose_name='Тренеры группы'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.child', verbose_name='Ребенок'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.pack', verbose_name='Пакет'),
        ),
    ]
