# Generated by Django 3.1.7 on 2021-03-19 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_auto_20210319_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.child', verbose_name='Ребенок'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.pack', verbose_name='Пакет'),
        ),
    ]
