# Generated by Django 3.1.7 on 2021-03-22 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_auto_20210319_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='children',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.child', verbose_name='Дети на тренировке'),
        ),
    ]
