# Generated by Django 3.1.7 on 2021-03-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_training_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='children',
        ),
        migrations.AddField(
            model_name='training',
            name='children',
            field=models.ManyToManyField(blank=True, default=None, to='mainapp.Child', verbose_name='Дети на тренировке'),
        ),
    ]
