# Generated by Django 3.1.7 on 2021-03-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_auto_20210322_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChildOnTraining',
        ),
    ]
