# Generated by Django 3.1.7 on 2021-03-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_delete_childontraining'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='group',
            new_name='groups',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='pack',
            new_name='packs',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='trainer',
            new_name='trainers',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='trainer',
            new_name='trainers',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='group',
            new_name='groups',
        ),
        migrations.AlterField(
            model_name='training',
            name='children',
            field=models.ManyToManyField(blank=True, default=None, to='mainapp.Child', verbose_name='Дети присутствовавшие на тренировке'),
        ),
    ]
