# Generated by Django 3.1.7 on 2021-08-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_schedule_suit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='suit',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
    ]
