# Generated by Django 3.1.7 on 2021-08-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_auto_20210819_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='train_day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], verbose_name='День тренировки'),
        ),
    ]
