# Generated by Django 3.1.7 on 2021-08-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0049_auto_20210819_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='day',
            new_name='train_day',
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('train_day', 'department', 'starttime', 'endtime')},
        ),
    ]
