# Generated by Django 3.1.7 on 2021-08-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_auto_20210819_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='endtime',
            field=models.TimeField(verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='training',
            name='starttime',
            field=models.TimeField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='training',
            name='status',
            field=models.CharField(choices=[('not_stated', 'Неопределенный'), ('done', 'Выполнена'), ('not_took_place', 'Не состоялась')], default='not_stated', max_length=14, verbose_name='Состояние'),
        ),
        migrations.AlterUniqueTogether(
            name='training',
            unique_together={('date', 'department', 'group', 'starttime', 'endtime')},
        ),
    ]
